services:
  julian-neo4j:
    image: neo4j:latest
    container_name: neo4j_db_1
    restart: always
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - ./import:/import
    networks:
      - network

  backend:
    build: ./backend
    container_name: express_backend
    restart: always
    depends_on:
      - julian-neo4j
    env_file:
      - .env
    ports:
      - "${EXPRESS_PORT}:3000"
    networks:
      - network

volumes:
  neo4j_data:
  
networks:
  network:
    driver: bridge
